In [1]:
#hill cipher forward pass
import numpy as np

In [2]:
mapping_dict = {
    "a": 0,
    "b": 1,
    "c": 2,
    "d": 3,
    "e": 4,
    "f": 5,
    "g": 6,
    "h": 7,
    "i": 8,
    "j": 9,
    "k": 10,
    "l": 11,
    "m": 12,
    "n": 13,
    "o": 14,
    "p": 15,
    "q": 16,
    "r": 17,
    "s": 18,
    "t": 19,
    "u": 20,
    "v": 21,
    "w": 22,
    "x": 23,
    "y": 24,
    "z": 25
}
reverse_mapping = {v:k for k,v in mapping_dict.items() }

In [3]:
raw_text = "Hello this is hill cipher encryption project"

stripped_space_text = raw_text.lower().replace(" ","")


In [4]:
#breaking text into pieces of 2
if len(stripped_space_text)%2 != 0:stripped_space_text+="x"

splitted_text_into_chunks = np.array([list(stripped_space_text[i-2:i]) for i in range(2,len(stripped_space_text)+1,2)])
mapping_chunks_to_numbers = np.array([list(map(lambda x:mapping_dict[str(x)],i)) for i in splitted_text_into_chunks]).T
print(mapping_chunks_to_numbers)


[[ 7 11 14  7 18 18  8 11  8  7 17 13 17 15  8 13 17  9  2]
 [ 4 11 19  8  8  7 11  2 15  4  4  2 24 19 14 15 14  4 19]]


In [5]:
key = np.array([[3,3],[2,5]])

applying_key_to_each_vector = []

for index in range(len(mapping_chunks_to_numbers[0])):
    column = mapping_chunks_to_numbers[:,index].reshape(2,-1)
    applying_key = (key@column)%26
    applying_key_to_each_vector.append(applying_key)


In [6]:
converted_back_to_letters = []
for vector in applying_key_to_each_vector:
    converted = []
    for value in vector:
        converted.append(reverse_mapping[int(value[0])])
    converted_back_to_letters.append(converted)

print(converted_back_to_letters)

[['h', 'i'], ['o', 'z'], ['v', 't'], ['t', 'c'], ['a', 'y'], ['x', 't'], ['f', 't'], ['n', 'g'], ['r', 'n'], ['h', 'i'], ['l', 'c'], ['t', 'k'], ['t', 'y'], ['y', 'v'], ['o', 'i'], ['g', 'x'], ['p', 'a'], ['n', 'm'], ['l', 'v']]


In [7]:
string_encrypted = ""
for each in converted_back_to_letters:
    string_encrypted += "".join(each)

print(string_encrypted)

hiozvttcayxtftngrnhilctktyyvoigxpanmlv


In [8]:
def gcd(numa,numb):
    numa,numb = int(numa),int(numb)
    factorsa = [i for i in range(1,numa) if numa%i ==0]
    factorsb = [i for i in range(1,numb) if numb%i ==0]
    intersection = set(factorsa).intersection(set(factorsb))
    return intersection == {1}

In [10]:
#finding key inverse matrix
# 9x = 26k + 1
def modulous_inverse(n):
    k=0
    while True:
        if (26*k+1)%n==0:
            return (26*k+1)/n
        k+=1

def find_modulus_inverse_of_matrix(matrix):
    ad_matrix = (np.linalg.inv(matrix)*np.linalg.det(matrix))%26
    det_key = round(np.linalg.det(matrix),2)
    if not gcd(det_key,26):
        return "invalid"
    modulus_inverse_det_key = modulous_inverse(det_key)
    mat_inverse = (modulus_inverse_det_key*ad_matrix)%26
    return mat_inverse

key_inverse = find_modulus_inverse_of_matrix(key)
verify = (key@key_inverse)%26
print(verify)

[[1. 0.]
 [0. 1.]]


In [11]:

inverse_splitted_text_into_chunks = np.array([list(string_encrypted[i-2:i]) for i in range(2,len(string_encrypted)+1,2)])
inverse_mapping_chunks_to_numbers = np.array([list(map(lambda x:mapping_dict[str(x)],i)) for i in inverse_splitted_text_into_chunks]).T
print(inverse_mapping_chunks_to_numbers)

[[ 7 14 21 19  0 23  5 13 17  7 11 19 19 24 14  6 15 13 11]
 [ 8 25 19  2 24 19 19  6 13  8  2 10 24 21  8 23  0 12 21]]


In [13]:


applying_key_inverse_to_each_vector = []

for index in range(len(inverse_mapping_chunks_to_numbers[0])):
    column = inverse_mapping_chunks_to_numbers[:,index].reshape(2,-1)
    applying_key = (key_inverse@column)%26
    applying_key_inverse_to_each_vector.append(applying_key)


In [14]:
converted_back_to_letters = []
for vector in applying_key_inverse_to_each_vector:
    converted = []
    for value in vector:
        converted.append(reverse_mapping[int(value[0])])
    converted_back_to_letters.append(converted)

print(converted_back_to_letters)

[['h', 'e'], ['l', 'l'], ['o', 't'], ['h', 'i'], ['s', 'i'], ['s', 'h'], ['i', 'l'], ['l', 'c'], ['i', 'p'], ['h', 'e'], ['r', 'e'], ['n', 'c'], ['r', 'y'], ['p', 't'], ['i', 'o'], ['n', 'p'], ['r', 'o'], ['j', 'e'], ['c', 't']]


In [16]:
string_decrypted = ""
for each in converted_back_to_letters:
    string_decrypted += "".join(each)

print(string_decrypted)

hellothisishillcipherencryptionproject


In [18]:
#attacker
p = [[7,11],
     [4,11]]
c = [[7,14],
     [8,25]]

p_inverse = find_modulus_inverse_of_matrix(p)
key = (c@p_inverse)%26
print(key)

[[3. 3.]
 [2. 5.]]
